# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefcafe_auth', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='beefcafe_auth.Group'),
        ),
    ]
