# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beefcafe_auth', '0003_auto_20171007_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beefcafe_auth.User'),
        ),
    ]
