# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefcafe_auth', '0004_auto_20171007_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='dn',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=300),
        ),
    ]
