# Generated by Django 3.0.5 on 2020-04-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beefcafe_auth', '0006_site_allow_unauthorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beefcafe_auth.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beefcafe_auth.User')),
            ],
            options={
                'unique_together': {('site', 'user')},
            },
        ),
    ]
