version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:Z
      - ./fullchain.pem:/fullchain.pem:Z
      - ./privkey.pem:/privkey.pem:Z
      - ./ca-chain.pem:/ca-chain.pem:Z
      - "static:/usr/share/nginx/html/static:Z"
    ports:
      - 80:80
      - 443:443

  auth_gateway:
    build: .
    environment:
      - "POSTGRES_PASSWORD=PASSWORD"
      - "POSTGRES_USER=authgateway"
      - "POSTGRES_DATABASE=authgateway"
      - "POSTGRES_HOST=postgres"
    volumes:
      - "static:/usr/src/app/static:Z"
      - "secret:/usr/src/app/secret:Z"

  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=PASSWORD"
      - "POSTGRES_USER=authgateway"
      - "POSTGRES_DATABASE=authgateway"

volumes:
  secret:
  static:
