version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:Z
      - ./fullchain.pem:/fullchain.pem:Z
      - ./privkey.pem:/privkey.pem:Z
      - ./jmg-root-ca.pem:/jmg-root-ca.pem:Z
      - "./static:/usr/share/nginx/html/static:Z"
    ports:
      - 443:443

  auth_gateway:
    build: .
    ports:
      # - 8000:8000
    environment:
      - "POSTGRES_PASSWORD={{REDACTED}}"
      - "POSTGRES_USER=authgateway"
      - "POSTGRES_DATABASE=authgateway"
      - "POSTGRES_HOST=postgres"
    volumes:
      - "./static:/usr/src/app/static:Z"

  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD={{REDACTED}}"
      - "POSTGRES_USER=authgateway"
      - "POSTGRES_DATABASE=authgateway"
